version: '3'
services:
  backend:
    container_name: uma_backend
    restart: always
    build:
      context: ./Uma-Backend
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    volumes:
      - ./Uma-Backend:/usr/src/app
    networks:
      - uma_network
    depends_on:
      - database

  database:
    container_name: uma_db
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - ./Uma-Backend/temporal/docker:/data/db
    logging:
      driver: none
    networks:
      - uma_network

  frontend:
    container_name: uma_frontend
    build:
      context: ./Uma-Project
      dockerfile: Dockerfile
    ports:
      - "4500:80"
    depends_on:
      - backend
    networks:
      - uma_network

networks:
  uma_network:
    driver: bridge